version: '3.0'

services:
  filebeat:
    build: ./filebeat/
    volumes:
      - "../logs/log-*.log:/var/log"
      - "../logs/log-*.log:/usr/share/filebeat/data:rw"
      - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

  logstash:
    build: ./logstash/
    expose:
     - 5044


volumes:
  filebeat_data:
